[package]
name = "image"
version = "0.1.0"
edition = "2024"

[features]
default = ["msr"]
msr = ["kernel/msr"]

[build-dependencies]
kernel = { path = "../kernel", artifact = "bin", target = "x86_64-unknown-none", default-features = false }
bootloader = "0.11.13"
